# config/packages/prod/fosuserbundle.yml
fos_user:
    registration: # hack from https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2667
        confirmation:
            enabled: false
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "noreply@supinternet.fr"
        sender_name: "Demo Name"