security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_TEACHER:     ROLE_USER
        ROLE_ADMIN:       ROLE_TEACHER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
            switch_user: { role: ROLE_ADMIN, parameter: _switch_user }

    access_control:
        - { path: ^/login$, allow_if: "!has_role('ROLE_USER')" }
        - { path: ^/register/confirmed, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, allow_if: "!has_role('ROLE_USER')" }
        - { path: ^/logged/out, allow_if: "!has_role('ROLE_USER')" }
        - { path: ^/student/only, allow_if: "!has_role('ROLE_TEACHER') && has_role('ROLE_USER')" }
        - { path: ^/teacher, role: ROLE_TEACHER }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/common, role: ROLE_USER }